### ISSUE TITLE
Displays 680 ilvl on all items.

### ISSUE THREAD

**Issue by hiarswe** [cogwerkz/Bagnon_ItemLevel#3] opened 2017-08-25 17:47 UTC
Hi.
I am using the 1.0.2-Release version of Bagnon ItemLevel, 7.2.6 of Bagnon, and as main UI i use ElvUI 10.59. When I look at my items, they all show 680, which is clearly not correct.

![bagnon_itemlevel](https://user-images.githubusercontent.com/31354942/29725875-f46bc92c-89cd-11e7-9e4d-5e4ab105e763.jpg)

Sometimes it does display correct. But I can't recreate when it works and not. Any thoughts would be appreciated.

Thanks.

**Comment by goldpaw** [comment] 2017-08-26 14:12
Could be a pure bug from my side, could be an addon incompatibility. I understand it can be hard to track down if it's not something that happens all the time, since a lack of the bug doesn't mean it's not there, just that it hasn't randomly fired yet. 

So, ElvUI, Bagnon, and Zygor? I'll start there, and look into it! :)

**Comment by bullsei** [comment] 2017-08-29 18:08
Should use GetDetailedItemLevelInfo() instead of GetItemInfo()

**Comment by goldpaw** [comment] 2017-09-04 00:46
Should in theory be fixed now, though I haven't been able to reproduce the bug myself. I do perform an extra check for upgraded items with GetDetailedItemLevelInfo now.

**Closed by goldpaw** 2017-09-04 00:46 UTC
Labels: bug
